// Code generated by MockGen. DO NOT EDIT.
// Source: course_note_service.go

// Package servicemocks is a generated GoMock package.
package servicemocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	service "github.com/jdpx/mind-hub-api/pkg/service"
	reflect "reflect"
)

// MockCourseNoteServicer is a mock of CourseNoteServicer interface
type MockCourseNoteServicer struct {
	ctrl     *gomock.Controller
	recorder *MockCourseNoteServicerMockRecorder
}

// MockCourseNoteServicerMockRecorder is the mock recorder for MockCourseNoteServicer
type MockCourseNoteServicerMockRecorder struct {
	mock *MockCourseNoteServicer
}

// NewMockCourseNoteServicer creates a new mock instance
func NewMockCourseNoteServicer(ctrl *gomock.Controller) *MockCourseNoteServicer {
	mock := &MockCourseNoteServicer{ctrl: ctrl}
	mock.recorder = &MockCourseNoteServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCourseNoteServicer) EXPECT() *MockCourseNoteServicerMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockCourseNoteServicer) Get(ctx context.Context, cID, uID string) (*service.CourseNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, cID, uID)
	ret0, _ := ret[0].(*service.CourseNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockCourseNoteServicerMockRecorder) Get(ctx, cID, uID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCourseNoteServicer)(nil).Get), ctx, cID, uID)
}

// Update mocks base method
func (m *MockCourseNoteServicer) Update(ctx context.Context, cID, uID, value string) (*service.CourseNote, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, cID, uID, value)
	ret0, _ := ret[0].(*service.CourseNote)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update
func (mr *MockCourseNoteServicerMockRecorder) Update(ctx, cID, uID, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCourseNoteServicer)(nil).Update), ctx, cID, uID, value)
}
