version: 0.2

env:
  variables:
    ENV: "${env}"
  parameter-store:
    TF_VAR_auth0_client_domain: "codebuild-auth0-domain"
    TF_VAR_auth0_client_id: "codebuild-auth0-client-id"
    TF_VAR_auth0_client_secret: "codebuild-auth0-client-secret"
    TF_VAR_auth0_user_default_password: "codebuild-auth0-user-default-password"
    TF_VAR_github_token: "codebuild-github-access-key"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/0.14.2/terraform_0.14.2_linux_amd64.zip"
      - "unzip -o terraform.zip"
      - cd "$CODEBUILD_SRC_DIR"

  build:
    commands:
      - make validate-terraform APP_ENV=$ENV TERRAFORM_ACTION=plan
      - make validate-terraform APP_ENV=$ENV TERRAFORM_ACTION=apply OPTS=-auto-approve
