version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13

  pre_build:
    commands:
      - make install
  build:
    commands:
      - make run/lint
      - make run/test
      - make build/lambdas -B

artifacts:
  files:
    - "**/*"
  name: "mind_hub_api_build_artifact"
  base-directory: dist
