// Code generated by MockGen. DO NOT EDIT.
// Source: course_progress_store.go

// Package storemocks is a generated GoMock package.
package storemocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	store "github.com/jdpx/mind-hub-api/pkg/store"
	reflect "reflect"
)

// MockCourseProgressRepositor is a mock of CourseProgressRepositor interface
type MockCourseProgressRepositor struct {
	ctrl     *gomock.Controller
	recorder *MockCourseProgressRepositorMockRecorder
}

// MockCourseProgressRepositorMockRecorder is the mock recorder for MockCourseProgressRepositor
type MockCourseProgressRepositorMockRecorder struct {
	mock *MockCourseProgressRepositor
}

// NewMockCourseProgressRepositor creates a new mock instance
func NewMockCourseProgressRepositor(ctrl *gomock.Controller) *MockCourseProgressRepositor {
	mock := &MockCourseProgressRepositor{ctrl: ctrl}
	mock.recorder = &MockCourseProgressRepositorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCourseProgressRepositor) EXPECT() *MockCourseProgressRepositorMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockCourseProgressRepositor) Get(ctx context.Context, cID, uID string) (*store.CourseProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, cID, uID)
	ret0, _ := ret[0].(*store.CourseProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockCourseProgressRepositorMockRecorder) Get(ctx, cID, uID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCourseProgressRepositor)(nil).Get), ctx, cID, uID)
}

// Start mocks base method
func (m *MockCourseProgressRepositor) Start(ctx context.Context, cID, uID string) (*store.CourseProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, cID, uID)
	ret0, _ := ret[0].(*store.CourseProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start
func (mr *MockCourseProgressRepositorMockRecorder) Start(ctx, cID, uID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCourseProgressRepositor)(nil).Start), ctx, cID, uID)
}
