// Code generated by MockGen. DO NOT EDIT.
// Source: step_progress_handler.go

// Package storemocks is a generated GoMock package.
package storemocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	store "github.com/jdpx/mind-hub-api/pkg/store"
	reflect "reflect"
)

// MockStepProgressRepositor is a mock of StepProgressRepositor interface
type MockStepProgressRepositor struct {
	ctrl     *gomock.Controller
	recorder *MockStepProgressRepositorMockRecorder
}

// MockStepProgressRepositorMockRecorder is the mock recorder for MockStepProgressRepositor
type MockStepProgressRepositorMockRecorder struct {
	mock *MockStepProgressRepositor
}

// NewMockStepProgressRepositor creates a new mock instance
func NewMockStepProgressRepositor(ctrl *gomock.Controller) *MockStepProgressRepositor {
	mock := &MockStepProgressRepositor{ctrl: ctrl}
	mock.recorder = &MockStepProgressRepositorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStepProgressRepositor) EXPECT() *MockStepProgressRepositorMockRecorder {
	return m.recorder
}

// GetStepProgress mocks base method
func (m *MockStepProgressRepositor) GetStepProgress(ctx context.Context, cID, uID string) (*store.StepProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStepProgress", ctx, cID, uID)
	ret0, _ := ret[0].(*store.StepProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStepProgress indicates an expected call of GetStepProgress
func (mr *MockStepProgressRepositorMockRecorder) GetStepProgress(ctx, cID, uID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStepProgress", reflect.TypeOf((*MockStepProgressRepositor)(nil).GetStepProgress), ctx, cID, uID)
}

// StartStep mocks base method
func (m *MockStepProgressRepositor) StartStep(ctx context.Context, cID, uID string) (*store.StepProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartStep", ctx, cID, uID)
	ret0, _ := ret[0].(*store.StepProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartStep indicates an expected call of StartStep
func (mr *MockStepProgressRepositorMockRecorder) StartStep(ctx, cID, uID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartStep", reflect.TypeOf((*MockStepProgressRepositor)(nil).StartStep), ctx, cID, uID)
}
